// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjohodtfezjfavsxaqxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qb2hvZHRmZXpqZmF2c3hhcXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTMwMTMsImV4cCI6MjA1OTI4OTAxM30.Ml9bqFdMw1Bmnu-VeNqGn35Og296v1f00FdAPLB5E3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);