
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpdgcblngkudnulefzag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwZGdjYmxuZ2t1ZG51bGVmemFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTUyMjEsImV4cCI6MjA2MTg3MTIyMX0.LwghYyJTZKf5WniiCcrgDnHvuKm3KkqeXs48Uwr6y3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
